# Generated by Django 4.1.7 on 2023-03-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('imap_host', models.CharField(max_length=100)),
                ('imap_port', models.CharField(max_length=5)),
                ('smtp_host', models.CharField(max_length=5)),
                ('pop3_host', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(max_length=100)),
                ('recipients_email', models.CharField(max_length=2048)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('date_sent', models.DateTimeField()),
            ],
        ),
    ]
