# Generated by Django 4.1.7 on 2023-03-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='smtp_port',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='pop3_host',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='smtp_host',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
